sudo: required
services:
  - docker

before_install: 
  - docker build -t zigoto/frontend-app:latest -f 04-frontend-app/docker/Dockerfile.dev .

script:
  - docker run -e CI=true zigoto/frontend-app:latest npm run test