version: '3'
services:
  frontend-app:
    container_name: frontend-app
    image: zigoto/frontend-app
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ..:/app
  frontend-app-tests:
    container_name: frontend-app-tests
    image: zigoto/frontend-app
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    volumes:
      - /app/node_modules
      - ..:/app
    command: ["npm", "run", "test"]