version: '3'
services:
  redis-server:
    image: redis
  node-app:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - redis-server
