version: '3'
services:
  redis-server:
    image: redis
  node-app:
    # Build the image locally with npm run docker:build 
    image: zigoto/docker-visits:latest
    restart: always
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - redis-server
